/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    
    @Test 
    public void testAddToDoEntry()
    {
        //App classUnderTest = new App();
        ToDoList myList = new ToDoList();

        String entry = "buy groceries";

        myList.add(new ToDoEntry(entry));
        assertEquals(entry, myList.getLastItem().toString());
    }





}
