/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    
    @Test 
    public void testAddToDoEntry()
    {
        //App classUnderTest = new App();
        ToDoList myList = new ToDoList();

        String entry = "buy groceries";

        myList.add(new ToDoEntry(entry));
        assertEquals(entry, myList.getLastItem().toString());
    }

    //delete list entry
    @Test
    public void testDeleteEntry()
    {
        // given
        ToDoList myList = new ToDoList();


        String entry = "buy food for Loki";
        myList.add(new ToDoEntry(entry)); // add item to the list

        int entryIndex = 0; //index i want deleted

        /*
        I had this type as String, editor suggested type ToDoEntry. Why?
        */
        ToDoEntry entryToDelete = myList.getEntry(entryIndex); // value of that index

        // when
        myList.remove(entryToDelete); // deletes that value

        // then
        assertEquals(false, myList.searchForEntry(entryToDelete)); // false indicates that value is no longer contained in list
    }



}
