/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    
    @Test 
    public void testAddToDoEntry()
    {
        //App classUnderTest = new App();
        ToDoList myList = new ToDoList();

        myList.add(new ToDoEntry("buy groceries"));
        assertEquals("buy groceries", myList.getLastItem().toString());
    }



}
